version: "3.3"

services:
  # MySQL
  mysql:
    image: mysql:latest
    volumes:
      - ./db-user.sql:/docker-entrypoint-initdb.d/init.sql
      - data-user:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123

  # PhpMyAdmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "89:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123

  # Mail
  maildev:
    image: maildev/maildev
    restart: always
    ports:
      - "1080:1080"

  # App Backend
  userbackend:
    image: buihien0109/user-backend:latest
    depends_on:
      - mysql
    restart: always
    ports:
      - "8899:8080"

    # App Frontend
  userfrontend:
    image: buihien0109/user-frontend:latest
    ports:
      - "3002:80"
    restart: always

volumes:
  data-user: